// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// half_vec
NumericVector half_vec(const NumericMatrix& M);
RcppExport SEXP _pdglasso_half_vec(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(half_vec(M));
    return rcpp_result_gen;
END_RCPP
}
// mat2vec
NumericVector mat2vec(const NumericMatrix& M);
RcppExport SEXP _pdglasso_mat2vec(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(mat2vec(M));
    return rcpp_result_gen;
END_RCPP
}
// admm_pdglasso_internal
List admm_pdglasso_internal(const NumericMatrix& S, NumericMatrix X, NumericVector lambda1, const NumericVector& lambda2, double rho1, double rho2, bool varying_rho1, bool varying_rho2, int max_iter, double eps_abs, double eps_rel, const std::string& acr_type, int n_row_F);
RcppExport SEXP _pdglasso_admm_pdglasso_internal(SEXP SSEXP, SEXP XSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP rho1SEXP, SEXP rho2SEXP, SEXP varying_rho1SEXP, SEXP varying_rho2SEXP, SEXP max_iterSEXP, SEXP eps_absSEXP, SEXP eps_relSEXP, SEXP acr_typeSEXP, SEXP n_row_FSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type rho1(rho1SEXP);
    Rcpp::traits::input_parameter< double >::type rho2(rho2SEXP);
    Rcpp::traits::input_parameter< bool >::type varying_rho1(varying_rho1SEXP);
    Rcpp::traits::input_parameter< bool >::type varying_rho2(varying_rho2SEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eps_abs(eps_absSEXP);
    Rcpp::traits::input_parameter< double >::type eps_rel(eps_relSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type acr_type(acr_typeSEXP);
    Rcpp::traits::input_parameter< int >::type n_row_F(n_row_FSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_pdglasso_internal(S, X, lambda1, lambda2, rho1, rho2, varying_rho1, varying_rho2, max_iter, eps_abs, eps_rel, acr_type, n_row_F));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pdglasso_half_vec", (DL_FUNC) &_pdglasso_half_vec, 1},
    {"_pdglasso_mat2vec", (DL_FUNC) &_pdglasso_mat2vec, 1},
    {"_pdglasso_admm_pdglasso_internal", (DL_FUNC) &_pdglasso_admm_pdglasso_internal, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_pdglasso(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
