#' Toy dataset generated through [simul.pdColG()] function
#'
#' Data simulated by using the function [simul.pdColG] with the following arguments:
#' * `p <- 20`
#' * `q <- p/2`
#' * `dens=0.3, type=c("v","i","a"), force=NULL`
#'
#' @format ## `toy_data`
#' A list containing three elements:
#' * pdColG, a \eqn{p \times p} matrix describing the coloured graphical model,
#' * K, the concentration matrix associated to the model,
#' * sample.data, a data frame with 60 rows and 20 columns.
#'
#' @source Generated by the package functions.
"toy_data"
