#' Toy dataset generated through [simul.pdColG()] function
#'
#' Data simulated by using the function [simul.pdColG] with the following arguments:
#' * `p <- 20`
#' * `q <- p/2`
#' * `dens=0.3, type=c("v","i","a"), force=NULL`
#'
#' @format ## `toy_data`
#' A data frame with 60 rows and 20 columns.
#'
#' @source Generated by the package functions.
"toy_data"
