# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Half-vectorization
#' @description Internal function. Half-vectorization operator, without the diagonal.
#' @param M symmetric matrix.
#' @return a vector.
#' @noRd
half_vec <- function(M) {
    .Call(`_pdglasso_half_vec`, M)
}

#' @title From symmetric matrix to vector
#' @description Internal function. Transforms a symmetric matrix into a vector.
#' @param M symmetric matrix.
#' @return a vector.
#' @noRd
mat2vec <- function(M) {
    .Call(`_pdglasso_mat2vec`, M)
}

#' @title ADMM graphical lasso algorithm for coloured GGMs for paired data
#' @description Internal function. Implements a double ADMM loop.
#' @param S numeric matrix
#' @param X numeric matrix
#' @param lambda1 numeric vector
#' @param lambda2 numeric vector
#' @param rho1 scalar
#' @param rho2 scalar
#' @param varying_rho1 logical
#' @param varying_rho2 logical
#' @param max_iter integer
#' @param eps_abs scalar
#' @param eps_rel scalar
#' @param acr_type character
#' @param n_row_F integer
#' @return a list
#' @noRd
admm_pdglasso_internal <- function(S, X, lambda1, lambda2, rho1, rho2, varying_rho1, varying_rho2, max_iter, eps_abs, eps_rel, acr_type, n_row_F) {
    .Call(`_pdglasso_admm_pdglasso_internal`, S, X, lambda1, lambda2, rho1, rho2, varying_rho1, varying_rho2, max_iter, eps_abs, eps_rel, acr_type, n_row_F)
}

